name: Deploy Frontend to S3

on:
  push:
    branches: ['dev'] # main 브랜치에 push 시 배포
  release:
    types: ['published']

jobs:
  build-and-deploy-to-s3:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Node.js LTS 20.x 설정
      - name: Set up Node.js LTS
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      # 환경변수 설정
      - name: Create .env.production
        run: |
          echo "VITE_API_BASE_URL=${{ secrets.VITE_API_BASE_URL }}" >> .env.production

      # 의존성 설치
      - name: Install dependencies
        run: npm ci

      # 프로젝트 빌드
      - name: Build project
        run: npm run build

      # AWS 자격 증명 설정
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      # S3 버킷으로 빌드 결과물 업로드
      - name: Sync build folder to S3
        run: |
          aws s3 sync ./dist s3://${{ secrets.S3_BUCKET_NAME }} --delete

      # CloudFront 캐시 무효화
      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.AWS_DISTRIBUTION_ID }} \
            --paths "/*"
